// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HqDVSIheR0XEGl9Fxyyd8TMi45YUSgc',
    appId: '1:163509759084:web:0a5ceece7429b22f96bc49',
    messagingSenderId: '163509759084',
    projectId: 'daleel-a82dc',
    authDomain: 'daleel-a82dc.firebaseapp.com',
    storageBucket: 'daleel-a82dc.firebasestorage.app',
    measurementId: 'G-BLKJR7J1LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh_6i1W9rGoNrLYLyeHh5pXLNNgsunLaE',
    appId: '1:163509759084:android:55f3aca8427197fd96bc49',
    messagingSenderId: '163509759084',
    projectId: 'daleel-a82dc',
    storageBucket: 'daleel-a82dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHuMVk4M7EXfiUXz0lRPEVBSoo2mF9f_M',
    appId: '1:163509759084:ios:9783db7cd1861a8e96bc49',
    messagingSenderId: '163509759084',
    projectId: 'daleel-a82dc',
    storageBucket: 'daleel-a82dc.firebasestorage.app',
    iosBundleId: 'com.example.daleelAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHuMVk4M7EXfiUXz0lRPEVBSoo2mF9f_M',
    appId: '1:163509759084:ios:9783db7cd1861a8e96bc49',
    messagingSenderId: '163509759084',
    projectId: 'daleel-a82dc',
    storageBucket: 'daleel-a82dc.firebasestorage.app',
    iosBundleId: 'com.example.daleelAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8HqDVSIheR0XEGl9Fxyyd8TMi45YUSgc',
    appId: '1:163509759084:web:0d90ebbf78d0b58496bc49',
    messagingSenderId: '163509759084',
    projectId: 'daleel-a82dc',
    authDomain: 'daleel-a82dc.firebaseapp.com',
    storageBucket: 'daleel-a82dc.firebasestorage.app',
    measurementId: 'G-76NFNXRM77',
  );
}
